//
// Generated file, do not edit! Created by opp_msgc 4.2 from messages/DataPkt.msg.
//

#ifndef _DATAPKT_M_H_
#define _DATAPKT_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0402
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif

// cplusplus {{
#include <ApplPkt_m.h>
// }}



/**
 * Class generated from <tt>messages/DataPkt.msg</tt> by opp_msgc.
 * <pre>
 * packet DataPkt extends ApplPkt {
 *     unsigned long seqNumber;
 *     bool policeman;
 *     long policemanId;
 * }
 * </pre>
 */
class DataPkt : public ::ApplPkt
{
  protected:
    unsigned long seqNumber_var;
    bool policeman_var;
    long policemanId_var;

  private:
    void copy(const DataPkt& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const DataPkt&);

  public:
    DataPkt(const char *name=NULL, int kind=0);
    DataPkt(const DataPkt& other);
    virtual ~DataPkt();
    DataPkt& operator=(const DataPkt& other);
    virtual DataPkt *dup() const {return new DataPkt(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual unsigned long getSeqNumber() const;
    virtual void setSeqNumber(unsigned long seqNumber);
    virtual bool getPoliceman() const;
    virtual void setPoliceman(bool policeman);
    virtual long getPolicemanId() const;
    virtual void setPolicemanId(long policemanId);
};

inline void doPacking(cCommBuffer *b, DataPkt& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, DataPkt& obj) {obj.parsimUnpack(b);}


#endif // _DATAPKT_M_H_
